### ISSUE TITLE
Share URL with code sample not possible

### ISSUE THREAD

**Issue by yobad** [codeboot-org/support#1]
Part of the demo for codeboot was the following link: 
https://app.codeboot.org/4.0.0/?init=.fc3F1YXJlcy0xLnB5~XQAAgAAlAAAAAAAAAAAzG8qmJ5VKcRIqc4D53n0GAajKdINri6XFtz6xpwkpsUNe9RxaVfxZX_7nGwA=.~lang=py-novice.a

This feature is not found in any of the recent version of codeboot. Can you please specify if this is a bug or if the feature is only existent in a specific version of codeboot? 

EDIT: The feature is there! Right click on the stepping button.

Thank you

**Comment by feeley** [comment]
I am glad you have found the answer to your question. We have prepared some slides that explain how to create such executable links: https://codeboot-org.github.io/presentations/keynote/fr/notes-de-cours-keynote.pdf

There are other useful examples of creating presentations with codeBoot here: https://codeboot-org.github.io/presentations/
