### ISSUE TITLE
F strings not supported 

### ISSUE THREAD

**Issue by yobad** [codeboot-org/support#3]
Hello in the context of teacher SN1 Programming in Science course, our department is using codeboot to teach science students but we noticed that f strings are not currently supported by codeboot:

Steps: 
1. Type the following lines in codeboot:  
```python
age = 25
print(f"bobby's age is {age}")
```
2.  Run

Output: Syntax error

**Comment by omelancon** [comment]
Hi @yobad! Thank you for the recent issues you have been filling.

It turns out I am working on the implementation of f-string right now. So this feature should be released soon.

**Comment by omelancon** [comment]
Python 3.12 f-strings will be supported in the next release (5.0.0) which is planned in the upcoming weeks.
